apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: miningpool-gateway-traefik-app-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: miningpool-gateway-traefik-app
    k8s.kuboard.cn/workload: miningpool-gateway-traefik-app
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-oplog@kubernetescrd,
      kube-system-strip-miningpool-gateway-prefix@kubernetescrd,
      kube-system-http-redirect-https@kubernetescrd,
      kube-system-common-headers@kubernetescrd,
      kube-system-headers-appid-to-body@kubernetescrd,
      kube-system-headers-userid-to-body@kubernetescrd,
      kube-system-headers-langid-to-body@kubernetescrd,
      kube-system-headers-app-login-token-to-body@kubernetescrd,
      kube-system-app-rbac-auth@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http: &http_rules
        paths:
          - path: "/api/miningpool/v1/create/apppool"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
          - path: "/api/miningpool/v1/get/apppool"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
          - path: "/api/miningpool/v1/get/apppools"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
          - path: "/api/miningpool/v1/get/n/apppools"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
          - path: "/api/miningpool/v1/delete/apppool"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
          - path: "/api/miningpool/v1/create/gooduser"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
          - path: "/api/miningpool/v1/get/gooduser"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
          - path: "/api/miningpool/v1/get/goodusers"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
          - path: "/api/miningpool/v1/update/gooduser"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
          - path: "/api/miningpool/v1/delete/gooduser"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
          - path: "/api/miningpool/v1/get/pools"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
          - path: "/api/miningpool/v1/get/pool"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
          - path: "/api/miningpool/v1/create/rootuser"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
          - path: "/api/miningpool/v1/get/rootuser"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
          - path: "/api/miningpool/v1/get/rootusers"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
          - path: "/api/miningpool/v1/update/rootuser"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
          - path: "/api/miningpool/v1/delete/rootuser"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
    - host: api.procyon.vip
      http: *http_rules
    - host: api.lpsecretbase.com
      http: *http_rules
    - host: api.ohhash.com
      http: *http_rules
    - host: api.procyon.xpool.top
      http: *http_rules
    - host: api.procyon.npool.top
      http: *http_rules
    - host: api.cryptomore.npool.top
      http: *http_rules
    - host: api.development.npool.top
      http: *http_rules
    - host: api.jh-testing.npool.top
      http: *http_rules
    - host: api.japan-procyon-production.npool.top
      http: *http_rules
    - host: api.hk-cryptomore-production.npool.top
      http: *http_rules
    - host: api.cryptomore.io
      http: *http_rules
    - host: api.mimo.biz
      http: *http_rules
    - host: api.epool.tech
      http: *http_rules

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: miningpool-gateway-traefik-app-user-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: miningpool-gateway-traefik-app-user
    k8s.kuboard.cn/workload: miningpool-gateway-traefik-app-user
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-oplog@kubernetescrd,
      kube-system-strip-miningpool-gateway-prefix@kubernetescrd,
      kube-system-http-redirect-https@kubernetescrd,
      kube-system-common-headers@kubernetescrd,
      kube-system-headers-appid-to-body@kubernetescrd,
      kube-system-headers-userid-to-body@kubernetescrd,
      kube-system-headers-langid-to-body@kubernetescrd,
      kube-system-headers-app-login-token-to-body@kubernetescrd,
      kube-system-app-user-role-rbac-auth@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http: &http_rules
        paths:
          - path: "/api/miningpool/v1/create/fraction"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
          - path: "/api/miningpool/v1/get/fraction"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
          - path: "/api/miningpool/v1/get/user/fractions"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
          - path: "/api/miningpool/v1/get/orderuser"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
          - path: "/api/miningpool/v1/update/orderuser"
            backend:
              serviceName: miningpool-gateway
              servicePort: 50860
    - host: api.procyon.vip
      http: *http_rules
    - host: api.lpsecretbase.com
      http: *http_rules
    - host: api.ohhash.com
      http: *http_rules
    - host: api.procyon.xpool.top
      http: *http_rules
    - host: api.procyon.npool.top
      http: *http_rules
    - host: api.cryptomore.npool.top
      http: *http_rules
    - host: api.development.npool.top
      http: *http_rules
    - host: api.jh-testing.npool.top
      http: *http_rules
    - host: api.japan-procyon-production.npool.top
      http: *http_rules
    - host: api.hk-cryptomore-production.npool.top
      http: *http_rules
    - host: api.cryptomore.io
      http: *http_rules
    - host: api.mimo.biz
      http: *http_rules
    - host: api.epool.tech
      http: *http_rules
