apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: miningpool-gateway-traefik-app-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: miningpool-gateway-traefik-app
    k8s.kuboard.cn/workload: miningpool-gateway-traefik-app
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-strip-miningpool-gateway-prefix@kubernetescrd,
      kube-system-http-redirect-https@kubernetescrd,
      kube-system-common-headers@kubernetescrd,
      kube-system-headers-appid-to-body@kubernetescrd,
      kube-system-headers-userid-to-body@kubernetescrd,
      kube-system-headers-langid-to-body@kubernetescrd,
      kube-system-headers-app-login-token-to-body@kubernetescrd,
      kube-system-app-rbac-auth@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http: &http_rules
        paths:
          - path: /api/g11n/v1/get/applangs
            backend:
              serviceName: miningpool-gateway
              servicePort: 50610
          - path: /api/g11n/v1/get/appcountries
            backend:
              serviceName: miningpool-gateway
              servicePort: 50610
          - path: /api/g11n/v1/get/messages
            backend:
              serviceName: miningpool-gateway
              servicePort: 50610
          - path: /api/g11n/v1/version
            backend:
              serviceName: miningpool-gateway
              servicePort: 50610
    - host: api.procyon.vip
      http: *http_rules
    - host: api.lpsecretbase.com
      http: *http_rules
    - host: api.ohhash.com
      http: *http_rules
    - host: api.procyon.xpool.top
      http: *http_rules
    - host: api.procyon.npool.top
      http: *http_rules
    - host: api.cryptomore.npool.top
      http: *http_rules
    - host: api.development.npool.top
      http: *http_rules
    - host: api.jh-testing.npool.top
      http: *http_rules
    - host: api.japan-procyon-production.npool.top
      http: *http_rules
    - host: api.hk-cryptomore-production.npool.top
      http: *http_rules
    - host: api.cryptomore.io
      http: *http_rules
    - host: api.mimo.biz
      http: *http_rules
    - host: api.epool.tech
      http: *http_rules

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: miningpool-gateway-traefik-app-user-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: miningpool-gateway-traefik-app-user
    k8s.kuboard.cn/workload: miningpool-gateway-traefik-app-user
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-oplog@kubernetescrd,
      kube-system-strip-miningpool-gateway-prefix@kubernetescrd,
      kube-system-http-redirect-https@kubernetescrd,
      kube-system-common-headers@kubernetescrd,
      kube-system-headers-appid-to-body@kubernetescrd,
      kube-system-headers-userid-to-body@kubernetescrd,
      kube-system-headers-langid-to-body@kubernetescrd,
      kube-system-headers-app-login-token-to-body@kubernetescrd,
      kube-system-app-user-role-rbac-auth@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http: &http_rules
        paths:
          - path: /api/g11n/v1/create
            backend:
              serviceName: miningpool-gateway
              servicePort: 50610
          - path: /api/g11n/v1/update
            backend:
              serviceName: miningpool-gateway
              servicePort: 50610
          - path: /api/g11n/v1/delete
            backend:
              serviceName: miningpool-gateway
              servicePort: 50610
          - path: /api/g11n/v1/get/app
            backend:
              serviceName: miningpool-gateway
              servicePort: 50610
          - path: /api/g11n/v1/get
            backend:
              serviceName: miningpool-gateway
              servicePort: 50610
    - host: api.procyon.vip
      http: *http_rules
    - host: api.lpsecretbase.com
      http: *http_rules
    - host: api.ohhash.com
      http: *http_rules
    - host: api.procyon.xpool.top
      http: *http_rules
    - host: api.procyon.npool.top
      http: *http_rules
    - host: api.cryptomore.npool.top
      http: *http_rules
    - host: api.development.npool.top
      http: *http_rules
    - host: api.jh-testing.npool.top
      http: *http_rules
    - host: api.japan-procyon-production.npool.top
      http: *http_rules
    - host: api.hk-cryptomore-production.npool.top
      http: *http_rules
    - host: api.cryptomore.io
      http: *http_rules
    - host: api.mimo.biz
      http: *http_rules
    - host: api.epool.tech
      http: *http_rules
